variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_BUILDER: "registry.gitlab.com/os4d/docker-builder:2.4"

stages:
  - lint
  - test
  - scan-code

.debug-rule:
  - when: always

.lint-rules:
  rules:
    - if: '$CI_COMMIT_MESSAGE=~ /skip_test/'
      when: never
    - if: '$CI_COMMIT_MESSAGE=~ /CI:(retest|force test)/'
      when: always
    - changes:
        - src/**/*
        - tests/**/*
        - pyproject.toml
        - mypy.ini


.test-rules:
  rules:
    - if: '$CI_COMMIT_MESSAGE=~ /skip_test/'
      when: never
    - if: '$CI_COMMIT_MESSAGE=~ /CI:(retest|force test)/'
      when: always
    - changes:
        - .gitlab-ci.yml
        - src/**/*
        - tests/**/*
        - pyproject.toml
        - pdm.lock

.exports: &exports
  - |
    # export envs
    export BC_BUILD_DATE=$(date +"%Y-%m-%d %H:%M")
    export BC_BUILD_TIMESTAMP=$(date +"%Y%m%d%H%M%S")
    export BC_LOCK_SHA=$(echo ${CI_CHECKSUM} | cut -c 1-8)
    export BC_VERSION=$(cat .bumpversion.cfg | grep '^current_version' | sed 's/.*= //')
    export BC_COMMIT_SHA=c-${CI_COMMIT_SHA}


lint:
  stage: lint
  image: "$DOCKER_BUILDER"
  extends:
    - .test-rules
  before_script:
    - *exports
  script:
    - echo -e "${TXT_HI_WHITE}Using Docker image ${TXT_HI_GREEN}${CI_JOB_IMAGE}${TXT_RESET}"
    - echo "run lint"
    - flake8 src/bitcaster --exit-zero --format=html --htmldir flake8/ --statistics --tee
    - black src/bitcaster --check > black.txt
    - mkdir -p public/junit
    - cp -R flake8 public/
  artifacts:
    when: always
    paths:
      - flake8/
      - black.txt
    expire_in: 5 days

bandit:
  image: "$DOCKER_BUILDER"
  stage: scan-code
  cache:
    paths:
      - .trivy-cache
  before_script:
    - *exports
  script:
    - echo "Scanning code..."
    - pip install bandit
    - bandit -c bandit.yaml --format html -o bandit.html -r src/
  artifacts:
    when: always
    paths:
      - bandit.html
    expire_in: 4 weeks


test:
  stage: test
  image: "${CI_REGISTRY_IMAGE}/builder-test:latest"
  extends:
    - .test-rules
  variables:
    TEST_DIR: tests/
    COVERAGE_FILE: "tests/.coverage_data"
    COVERAGE_RCFILE: "tests/.coveragerc"
  before_script:
    - *exports
  script:
    - |
      # some info
      echo "run tests in '${TEST_DIR}'"
      echo -e "${TXT_HI_WHITE}Using Docker image ${TXT_HI_GREEN}${CI_JOB_IMAGE}${TXT_RESET}"
      echo "Version  ${BC_VERSION}"
      echo "Date     ${BC_BUILD_DATE}"
      echo "Tag      ${DOCKER_IMAGE_TAG}"
      echo "Checksum `cat /CHECKSUM`"
      echo "Tag      ${DOCKER_IMAGE_TAG}"
    - pytest tests/
      -ra
      --maxfail 10
      --migrations
      --junitxml=.build/junit/junit.xml
      --html=.build/junit/report.html
      --cov
      --cov-report=html
      --cov-report=xml
      --cov-report=term:skip-covered
    - pip install codecov
    - codecov -t $CODECOV_TOKEN
  after_script:
    - mkdir -p public
    - cp -R ./.build/* public
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    when: always
    reports:
      junit: public/junit/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - public
    expire_in: 5 days


checkCoverage:
  stage: test
  image: alpine:latest
  allow_failure: true
  extends:
    - .test-rules
  variables:
    JOB_NAME: test
    TARGET_BRANCH: develop
    URL_ACTUAL_PIPELINE: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/pipelines/${CI_PIPELINE_ID}/jobs?private_token=${GITLAB_API_TOKEN}
    URL_PIPELINES: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/pipelines?ref=${TARGET_BRANCH}&status=success&private_token=${GITLAB_API_TOKEN}
  needs:
    - test
  before_script:
    - apk add --update --no-cache curl jq
  script:
    - | # ------
      echo "URL_PIPELINES $URL_PIPELINES"
      echo "URL_ACTUAL_PIPELINE $URL_ACTUAL_PIPELINE"
    - LATEST_PIPELINE_ID=`curl -s $URL_PIPELINES | jq ".[0].id"`
    - URL_LATEST_PIPELINE="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/pipelines/${LATEST_PIPELINE_ID}/jobs?private_token=${GITLAB_API_TOKEN}"
    - LATEST_COVERAGE=`curl -s $URL_LATEST_PIPELINE | jq --arg JOB_NAME "$JOB_NAME" '.[] | select(.name==$JOB_NAME) | .coverage'`
    - ACTUAL_COVERAGE=`curl -s $URL_ACTUAL_PIPELINE | jq --arg JOB_NAME "$JOB_NAME" '.[] | select(.name==$JOB_NAME) | .coverage'`
    - echo "COVERAGE:"
    - echo "Latest ${LATEST_COVERAGE}"
    - echo "Actual ${ACTUAL_COVERAGE}"
    - if  [ "$ACTUAL_COVERAGE" -lt "$LATEST_COVERAGE" ]; then echo "Coverage decreased from ${LATEST_COVERAGE} to ${ACTUAL_COVERAGE}" && exit 1; fi;
