[tox]
requires =
    tox>=4.2
    tox-gh-actions
    tox-uv>=1.20.2
env_list =
    lint
    py314
    py313
    py312
    py310
    docs
    mypy
    pkg_meta
skip_missing_interpreters = true

[testenv]
pass_env =
    CELERY_BROKER_URL
    PYTHONDONTWRITEBYTECODE
change_dir = {toxinidir}
commands =
    pytest -x {posargs:tests --junit-xml=junit.xml -o junit_family=legacy}
    diff-cover coverage.xml --compare-branch=origin/develop --fail-under=100
dependency_groups = dev

[testenv:lint]
description = run static analysis and style check using ruff
skip_install = true
deps =
    pre-commit-uv>=4.1.1
pass_env =
    HOMEPATH
    PROGRAMDATA
commands =
    pre-commit run --all-files --show-diff-on-failure

[testenv:docs]
description = build mkdocs documentation
skip_install = false
pass_env =
    DYLD_LIBRARY_PATH
commands =
    mkdocs build {posargs:}
dependency_groups = docs

[testenv:mypy]
description = run mypy type checking
skip_install = false
set_env =
    SECRET_KEY = super-secret-key-just-for-testing
commands =
    mypy --config-file mypy.ini {posargs:}
dependency_groups = typing
no_default_groups = false
uv_sync_flags = --no-editable

[testenv:pkg_meta]
description = check that the long description is valid
skip_install = true
deps =
    check-manifest
    check-wheel-contents>=0.6
    twine>=5.1.1
    uv>=0.5
commands =
    check-manifest
    uv build --sdist --wheel --out-dir {env_tmp_dir} .
    twine check {env_tmp_dir}{/}*
    check-wheel-contents --ignore W002 --no-config {env_tmp_dir}
