name: Test

on:
    push:
        branches:
            - develop
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   uses: actions/setup-python@v2

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip flake8
            -   name: Lint with flake8
                run: |
                    flake8 src/

    test:
        #        if: ${{github.event}} && ${{ !contains(github.event.head_commit.message, 'ci skip') }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: [ 3.8, 3.9 ]
        env:
            PY_VER: ${{ matrix.python-version}}
            BITCASTER_AEP: http://xxxxxxxxxxx@localhost:8000/api/o/bitcaster/a/38/
            BITCASTER_SDT: http://yyyyyyyyyyy@localhost:8000/api/o/bitcaster/

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip poetry
                    poetry install

            -   name: Test with pytest
                run: poetry run pytest tests/

            -   uses: codecov/codecov-action@v1
                with:
                    files: ./coverage1.xml,./coverage2.xml # optional
                    flags: unittests # optional
                    name: codecov-umbrella # optional
                    fail_ci_if_error: true # optional (default = false)
                    verbose: true # optional (default = false)
